# Generated by Django 3.2.5 on 2021-07-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordipost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coode',
            old_name='accountid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='accountid',
            new_name='user',
        ),
    ]
