# Generated by Django 3.2.5 on 2021-07-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordipost', '0002_auto_20210724_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
