# Generated by Django 3.2.6 on 2021-08-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordipost', '0003_remove_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytrend',
            name='myimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='munthtrend',
            name='myimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='notice',
            name='myimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='daytrend',
            name='daytrend',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='marking',
            name='myimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
