# Generated by Django 3.2.6 on 2021-08-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordipost', '0004_auto_20210819_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='sns',
            name='myimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='marking',
            name='lower',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='marking',
            name='outfitscore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='marking',
            name='upper',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
