# Generated by Django 3.2.6 on 2021-08-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordipost', '0006_marking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marking',
            old_name='todeypoint',
            new_name='todaypoint',
        ),
    ]
